# Generated by Django 4.0.4 on 2022-04-22 02:30

from django.db import migrations, models
import django.db.models.deletion
import panaderia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True)),
                ('precio', models.FloatField()),
                ('cantidad', models.SmallIntegerField()),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Targeta', 'Targeta')], default='Efectivo', max_length=8)),
                ('total', models.FloatField()),
                ('nombres', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=150, null=True)),
                ('cajas', models.JSONField(default=[])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=panaderia.models.upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='panaderia.caja')),
            ],
        ),
    ]
