# Generated by Django 4.0.4 on 2022-04-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
